p = input("enter prinsiple::::")
r = input("enter rate::::")
t = input("enter time dulation::::")
n = input("enter  number of input::::")
ci = int(p)*1+int(r)/100*int(n)**(int(n)*int(t))
print("compound intrast::::",ci)